"""empty message

Revision ID: 0474c5cbbca7
Revises: 
Create Date: 2019-12-09 20:21:36.100783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0474c5cbbca7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Administrator',
    sa.Column('AID', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('AID')
    )
    op.create_table('Book',
    sa.Column('BID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bName', sa.Text(), nullable=True),
    sa.Column('Category', sa.String(length=20), nullable=True),
    sa.Column('ISBN', sa.String(length=20), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('publicationDate', sa.DATE(), nullable=True),
    sa.Column('press', sa.String(length=40), nullable=True),
    sa.Column('sum', sa.Integer(), nullable=True),
    sa.Column('currNum', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(length=40), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('BID'),
    sa.UniqueConstraint('ISBN')
    )
    op.create_table('Classify',
    sa.Column('CID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classify', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('CID')
    )
    op.create_table('Person',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Reader',
    sa.Column('RID', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('rName', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=20), nullable=True),
    sa.Column('major', sa.String(length=20), nullable=True),
    sa.Column('borrowNum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('RID')
    )
    op.create_table('BorrowRecord',
    sa.Column('BID', sa.Integer(), nullable=False),
    sa.Column('RID', sa.String(length=20), nullable=False),
    sa.Column('borrowTime', sa.DATE(), nullable=False),
    sa.Column('deadLine', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['BID'], ['Book.BID'], ),
    sa.ForeignKeyConstraint(['RID'], ['Reader.RID'], ),
    sa.PrimaryKeyConstraint('BID', 'RID', 'borrowTime')
    )
    op.create_table('ReadRecord',
    sa.Column('BID', sa.Integer(), nullable=False),
    sa.Column('RID', sa.String(length=20), nullable=False),
    sa.Column('borrowTime', sa.DATE(), nullable=False),
    sa.Column('backDate', sa.DATE(), nullable=True),
    sa.Column('punish', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['BID'], ['Book.BID'], ),
    sa.ForeignKeyConstraint(['RID'], ['Reader.RID'], ),
    sa.PrimaryKeyConstraint('BID', 'RID', 'borrowTime')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ReadRecord')
    op.drop_table('BorrowRecord')
    op.drop_table('Reader')
    op.drop_table('Person')
    op.drop_table('Classify')
    op.drop_table('Book')
    op.drop_table('Administrator')
    # ### end Alembic commands ###
