"""empty message

Revision ID: 94656abda898
Revises: 0474c5cbbca7
Create Date: 2019-12-09 20:22:50.575291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94656abda898'
down_revision = '0474c5cbbca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Administrator',
    sa.Column('AID', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('AID')
    )
    op.create_table('Book',
    sa.Column('BID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bName', sa.Text(), nullable=True),
    sa.Column('Category', sa.String(length=20), nullable=True),
    sa.Column('ISBN', sa.String(length=20), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('publicationDate', sa.DATE(), nullable=True),
    sa.Column('press', sa.String(length=40), nullable=True),
    sa.Column('sum', sa.Integer(), nullable=True),
    sa.Column('currNum', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(length=40), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('BID'),
    sa.UniqueConstraint('ISBN')
    )
    op.create_table('Classify',
    sa.Column('CID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classify', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('CID')
    )
    op.create_table('Person',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Reader',
    sa.Column('RID', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('rName', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=20), nullable=True),
    sa.Column('major', sa.String(length=20), nullable=True),
    sa.Column('borrowNum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('RID')
    )
    op.create_table('BorrowRecord',
    sa.Column('BID', sa.Integer(), nullable=False),
    sa.Column('RID', sa.String(length=20), nullable=False),
    sa.Column('borrowTime', sa.DATE(), nullable=False),
    sa.Column('deadLine', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['BID'], ['Book.BID'], ),
    sa.ForeignKeyConstraint(['RID'], ['Reader.RID'], ),
    sa.PrimaryKeyConstraint('BID', 'RID', 'borrowTime')
    )
    op.create_table('ReadRecord',
    sa.Column('BID', sa.Integer(), nullable=False),
    sa.Column('RID', sa.String(length=20), nullable=False),
    sa.Column('borrowTime', sa.DATE(), nullable=False),
    sa.Column('backDate', sa.DATE(), nullable=True),
    sa.Column('punish', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['BID'], ['Book.BID'], ),
    sa.ForeignKeyConstraint(['RID'], ['Reader.RID'], ),
    sa.PrimaryKeyConstraint('BID', 'RID', 'borrowTime')
    )
    op.drop_table('readrecord')
    op.drop_table('reader')
    op.drop_table('borrowrecord')
    op.drop_table('classify')
    op.drop_table('person')
    op.drop_table('administrator')
    op.drop_index('ISBN', table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('BID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('bName', mysql.TEXT(), nullable=True),
    sa.Column('Category', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('ISBN', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('author', mysql.TEXT(), nullable=True),
    sa.Column('publicationDate', sa.DATE(), nullable=True),
    sa.Column('press', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('sum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('currNum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('link', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('page', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('BID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ISBN', 'book', ['ISBN'], unique=True)
    op.create_table('administrator',
    sa.Column('AID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('AID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('person',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('classify',
    sa.Column('CID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('classify', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('CID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('borrowrecord',
    sa.Column('BID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('RID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('borrowTime', sa.DATE(), nullable=False),
    sa.Column('deadLine', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['BID'], ['book.BID'], name='borrowrecord_ibfk_1'),
    sa.ForeignKeyConstraint(['RID'], ['reader.RID'], name='borrowrecord_ibfk_2'),
    sa.PrimaryKeyConstraint('BID', 'RID', 'borrowTime'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reader',
    sa.Column('RID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('rName', mysql.TEXT(), nullable=True),
    sa.Column('department', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('major', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('borrowNum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('RID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('readrecord',
    sa.Column('BID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('RID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('borrowTime', sa.DATE(), nullable=False),
    sa.Column('backDate', sa.DATE(), nullable=True),
    sa.Column('punish', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['BID'], ['book.BID'], name='readrecord_ibfk_1'),
    sa.ForeignKeyConstraint(['RID'], ['reader.RID'], name='readrecord_ibfk_2'),
    sa.PrimaryKeyConstraint('BID', 'RID', 'borrowTime'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('ReadRecord')
    op.drop_table('BorrowRecord')
    op.drop_table('Reader')
    op.drop_table('Person')
    op.drop_table('Classify')
    op.drop_table('Book')
    op.drop_table('Administrator')
    # ### end Alembic commands ###
